### ISSUE TITLE
Test run stuck in Running state no interim results displayed on console

### ISSUE THREAD

**Issue by ayamakh123** [aws-solutions/distributed-load-testing-on-aws#115]
**Describe the bug**
We have scheduled a test run that started 2022-12-03 03:00:05, with Ramp up of 60m and Hold for 3540m. It should have completed on the 2022.12.05 but it never did and still is running. No interim results are posted on console - can't see whether anything run or not in the console, but based on Cloudwatch logs, it seems that test has finished on 2022.12.05 at 7am PDT.  

**To Reproduce**
Run a test for three regions with task counts: 
us-west-2 : 1
ap-southeast-2 : 1
eu-west-1 : 1
and concurrency:
us-west-2 : 30
ap-southeast-2 : 30
eu-west-1 : 30
Ramp up 60m, Hold for 3540m.

**Expected behavior**
Test to complete and display logs on console in allotted time.

**Please complete the following information about the solution:**
- [x] Version: v3.1.1
- [x] Region: ca-central-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/A
- [x] Were there any errors in the CloudWatch Logs? Yes:

```
2022-12-02T00:47:31.724Z	9a83b96d-3959-4d46-95c4-ab2648fdbce7	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'region' of undefined",
    "stack": [
        "TypeError: Cannot read property 'region' of undefined",
        "    at Runtime.exports.handler (/var/task/index.js:14:39)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)"
    ]
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/119963130/205982267-881c2c6f-374f-403e-899b-bb1e34e1ec38.png)
![image](https://user-images.githubusercontent.com/119963130/205982313-c8cb5ac9-58c2-4857-a562-bd1f9e99928d.png)

**Additional context**

**Comment by ayamakh123** [comment]
Hi @G-Lenz 
Thank you for looking into this.
- Cloud Watch log belongs to DLTLambdaFunctionTaskCanceler4E12BDA6 ("[/aws/lambda/dlt-v3-canada-DLTLambdaFunctionTaskCanceler4E12BDA-86dHeUrghzSo]" Log group), and we did not customize anything, just running tests from a console.
- For the clusters in each region: In the DLT and AWS console, they showed no tasks running.
- Step function we have in the resources: DLTStepFunctionTaskRunnerStepFunctionsC295A535. Execution status: Failed.

![image](https://user-images.githubusercontent.com/119963130/207461479-8c2105f7-72f7-40ec-9df0-ae0a0ea225df.png)
![image](https://user-images.githubusercontent.com/119963130/207461928-b6525c15-ae9d-48b1-a6af-25f8e7f9495b.png)


We also encountered another oddity: after cancelling that stuck job - it is now stuck on "Cancelling" status. 
![image](https://user-images.githubusercontent.com/119963130/207449193-f8658f47-5e14-4724-8018-e5c5edb8d5c1.png)

**Comment by G-Lenz** [comment]
@ayamakh123 
Thank you for the information, it is very helpful. We are currently looking into this issue and will follow up when we have identified the bug or if we need any further info.

**Comment by G-Lenz** [comment]
Hi @ayamakh123

We have identified the issue that is causing the problem. The first and main issue is that you have reached the step functions event history limit as you noted above. The main reason for this is that the Step Fucntions workflow polls for the status of the test every minute for each region. This involves 3 different events (a Lambda function, a conditional, and a 1 minute wait between checks). The test was run for 3,600 minutes and in 3 regions. 3,600 minutes * 3 events per minute * 3 regions =. 32,400 steps just on the task status checking step. This exceeds the Sep Functions event history limit of 25,000. We have taken added this bug to our backlog and will include a fix for this in the next release.

As for the taskCanceler Lambda error, this is a separate issue and can be fixed by modifying the apiServices lambda. lines 1093 and 1094 need to be changed in `source/api-services/lib/scenarios/index.js`

The line currently looks like this:

```
Payload: JSON.stringify({
  testId: testId,
  region: regionalConfig.region,
  taskCluster: regionalConfig.taskCluster
})
```

and it should be:


```
Payload: JSON.stringify({
  testId: testId,
  testTaskConfig: regionalConfig
})
```

We also plan to include this change in the next release.

**Comment by ayamakh123** [comment]
Hi @G-Lenz,
Thank you for the update and for looking into this issue. We'll be looking forward to the next release.
