### ISSUE TITLE
Failed to run test with JMeter Selenium Webdriver Plugin

### ISSUE THREAD

**Issue by NEC-Maeta** [aws-solutions/distributed-load-testing-on-aws#116]
Related to
https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/74

jmeter 5.4.3
selenium webdriver 4.5.1

・Test failed even with chromeriver for Linux
・I was able to confirm from the log that chromedriver is running
・There was a problem after that.

cloudwatch log
2022-12-13 04:08:32,094 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'jp@gc - WebDriver Sampler'.
★
java.lang.IllegalArgumentException: Browser has not been configured.  Please ensure at least 1 WebDriverConfig is created for a ThreadGroup.
★
	at com.googlecode.jmeter.plugins.webdriver.sampler.WebDriverSampler.sample(WebDriverSampler.java:63) ~[jmeter-plugins-webdriver-4.5.1.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:829) [?:?]

I assume the browser is failing to start because Google Chrome is not installed in the container image.
If my assumptions are not wrong, I think I need to create a container image that installs Google Chrome.
Does anyone have a track record of success with WebDriver Sampler scenarios?
Or is it not supported yet?

Other done
・The script has been confirmed to work with JMeter GUI
・Enable headless mode
・Execution permission of chromedriver

**Comment by NEC-Maeta** [comment]
superfluous
・If you upload a zip created with Windows Client, an error will occur because the execution right (permission 644?) of chromedriver will be removed.

For this reason, we are uploading a zip created on Linux.
"Isn't it better to add chmod +x to the deployment script?"

**Comment by NEC-Maeta** [comment]
自己解決しました

・dockerfileにchrome/chromedriverをインストール

zipファイルにchromedriverを含めるとパーミッションが644になるためエラー

Dockerfile内で処理

dockerfile例

RUN apt update \
  && apt install -y gnupg \
  && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && apt install -y ./google-chrome-stable_current_amd64.deb \
  && apt clean \
  && rm -rf /var/lib/apt/lists/ \
  && rm google-chrome-stable_current_amd64.deb

RUN curl -O https://chromedriver.storage.googleapis.com/$(/usr/bin/google-chrome --version | awk '{print $3}')/chromedriver_linux64.zip
RUN unzip ./chromedriver_linux64.zip
